apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  ports:
    - port: 3001
  selector:
    app: calcbackend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calcbackend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: calcbackend
    spec:
      containers:
      - image: hellodemodz234.azurecr.io/calcbackend:latest
        name: calcbackend
        ports:
        - containerPort: 3001
        env: 
        - 
          name: "INSIGHTS"
          value: "false"
      imagePullSecrets:
      - name: kuberegistry